import json
import logging
import os
from datetime import datetime
from io import BytesIO
from typing import Any
from zipfile import ZIP_DEFLATED, ZipFile

from dotenv import load_dotenv
from telegram import (
    InputFile,
    KeyboardButton,
    MenuButtonWebApp,
    ReplyKeyboardMarkup,
    Update,
    WebAppInfo,
)
from telegram.ext import (
    Application,
    CommandHandler,
    ContextTypes,
    MessageHandler,
    filters,
)

load_dotenv()

logging.basicConfig(
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger("minibot")
logging.getLogger("httpx").setLevel(logging.WARNING)

BOT_TOKEN = os.getenv("BOT_TOKEN", "").strip()
WEBAPP_URL = os.getenv("WEBAPP_URL", "").strip()


def build_mod_zip(items: dict[str, str], user_id: int | None) -> BytesIO:
    now = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [f"{k} => {v}" for k, v in items.items()]
    payload = {
        "type": "chaymod",
        "user_id": user_id,
        "count": len(items),
        "generated_at_utc": now,
        "items": items,
    }

    buf = BytesIO()
    with ZipFile(buf, mode="w", compression=ZIP_DEFLATED) as zf:
        zf.writestr("mod_items.txt", "\n".join(lines) + "\n")
        zf.writestr("payload.json", json.dumps(payload, ensure_ascii=False, indent=2))
        zf.writestr(
            "README.txt",
            "Generated by minibot demo backend. Replace this with your real mod build pipeline.\n",
        )
    buf.seek(0)
    return buf


def clear_proxy_env() -> None:
    # Some environments inject SOCKS proxy vars; PTB then requires socks extras.
    for key in (
        "ALL_PROXY",
        "all_proxy",
        "HTTP_PROXY",
        "http_proxy",
        "HTTPS_PROXY",
        "https_proxy",
    ):
        os.environ.pop(key, None)


def build_keyboard() -> ReplyKeyboardMarkup:
    if not WEBAPP_URL:
        return ReplyKeyboardMarkup(
            [[KeyboardButton("/webapp")]],
            resize_keyboard=True,
        )

    return ReplyKeyboardMarkup(
        [[KeyboardButton(text="🚀 Mở Mini App", web_app=WebAppInfo(url=WEBAPP_URL))]],
        resize_keyboard=True,
        is_persistent=True,
    )


async def set_menu_button(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not WEBAPP_URL:
        return
    chat = update.effective_chat
    if chat is None:
        return

    await context.bot.set_chat_menu_button(
        chat_id=chat.id,
        menu_button=MenuButtonWebApp(text="Mở Mini App", web_app=WebAppInfo(url=WEBAPP_URL)),
    )


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await set_menu_button(update, context)

    text = "Bot đã sẵn sàng."
    if not WEBAPP_URL:
        text += "\n\nThiếu WEBAPP_URL trong file .env."
    else:
        text += "\n\nNếu app bật ra trình duyệt, hãy mở bằng nút Menu (góc phải thanh nhập) hoặc nút 🚀 trong chat."

    await update.message.reply_text(text, reply_markup=build_keyboard())


async def webapp(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    if not WEBAPP_URL:
        await update.message.reply_text("Thiếu WEBAPP_URL trong file .env.")
        return

    await set_menu_button(update, context)

    await update.message.reply_text(
        "Bấm nút bên dưới để mở Mini App.",
        reply_markup=build_keyboard(),
    )


async def handle_web_app_data(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    data = update.effective_message.web_app_data.data
    logger.info("WEB_APP_DATA: %s", data)

    try:
        payload: Any = json.loads(data)
    except json.JSONDecodeError:
        await update.effective_message.reply_text("Đã nhận dữ liệu nhưng không đúng JSON.")
        return

    kind = payload.get("type", "unknown")

    if kind == "chaymod":
        items = payload.get("items")
        if not isinstance(items, dict) or not items:
            await update.effective_message.reply_text("Không có mục mod hợp lệ trong yêu cầu.")
            return

        await update.effective_message.reply_text(
            f"Đã nhận {len(items)} mục. Đang đóng gói file ZIP..."
        )

        zip_buf = build_mod_zip(items, update.effective_user.id if update.effective_user else None)
        filename = f"MOD_LQ_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.zip"

        await context.bot.send_document(
            chat_id=update.effective_chat.id,
            document=InputFile(zip_buf, filename=filename),
            caption="✅ Đã tạo file ZIP từ yêu cầu Mini App.",
        )
        return

    if kind == "checkvip":
        await update.effective_message.reply_text("🔎 VIP: bản demo backend chưa tích hợp dữ liệu VIP.")
        return

    if kind == "synccart":
        await update.effective_message.reply_text("🔄 Giỏ hàng đã đồng bộ (demo).")
        return

    if kind == "clearcart":
        await update.effective_message.reply_text("🧹 Đã xoá giỏ (demo).")
        return

    if kind == "admin":
        action = payload.get("action", "unknown")
        await update.effective_message.reply_text(f"⚙️ Đã nhận lệnh admin: {action} (demo).")
        return

    await update.effective_message.reply_text(f"Đã nhận lệnh: {kind}")


async def handle_non_command_message(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    msg = update.effective_message
    if msg is None:
        return

    if msg.web_app_data and msg.web_app_data.data:
        logger.info("Fallback handler caught WEB_APP_DATA")
        await handle_web_app_data(update, context)
        return

    logger.info(
        "Non-command message: chat_id=%s text=%r",
        update.effective_chat.id if update.effective_chat else None,
        msg.text,
    )


async def unknown(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.message.reply_text("Lệnh không hợp lệ. Dùng /start hoặc /webapp.")


def main() -> None:
    if not BOT_TOKEN:
        raise RuntimeError("Thiếu BOT_TOKEN trong file .env")

    clear_proxy_env()

    app = Application.builder().token(BOT_TOKEN).build()

    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("webapp", webapp))
    app.add_handler(
        MessageHandler(filters.StatusUpdate.WEB_APP_DATA, handle_web_app_data)
    )
    app.add_handler(MessageHandler(~filters.COMMAND, handle_non_command_message))
    app.add_handler(MessageHandler(filters.COMMAND, unknown))

    logger.info("Starting bot...")
    app.run_polling(allowed_updates=Update.ALL_TYPES)


if __name__ == "__main__":
    main()
